### ISSUE TITLE
examples for Kickstart 1.3 are broken

### ISSUE THREAD

**Issue by Slamy** [bebbo/amigaos-cross-toolchain#25] opened 2017-05-29 14:31 UTC
I'll assume this has no high priority for this project as your intention is OS 3.x.
But still the examples say that kickstart 1.3 should be supported. They also use -m68000 as parameter.

Running hello-stdio clearly says "Need a 68020 or higher CPU" when executed on a plain A500.
But hello-ks13 crashes with `#00000003`.
And hello-stdio.nix13 crashes with `#00000004`.

When equipping an A500 with 68020:
hello-ks13 it will print the expected string but hang up after that.
hello-stdio.nix13 still just crashes with `#00000004`.
hello-stdio just says "Need version 37 of" which does make sense.

**Comment by bebbo** [comment] 2017-05-29 21:20
there was also a `-m68040` parameter passed to as... Thus relative branches were 32bit branches.

Please test

**Comment by Slamy** [comment] 2017-05-30 18:21
Both Kick 1.3 examples are working now. If I reduce my own project to C files they also work under Kick 1.3 now. Thank you. 
Strangely -O1 is broken now. It did work before. Shall I add another issue for that?
I tried to corner it with -fXXX options but I still don't get which exact optimization is the problem. Returns from some functions seem to crash. But no guru.... I will try to investigate.

**Comment by bebbo** [comment] 2017-05-30 19:04
If you could provide an example:
* a file named test.c (plus own headers if required)
* the exact command to reproduce the bug
I'd look into it.

The bug is probably in my own optimizer, use `-fbbb=+v` to get some verbose output. The letter indicates which optimizer is used. Then you can enable only specific optimizers e.g. `-fbbb=aspev` or disable them all with `-fbbb=-`. If you want more information in generated asm code, use upper case`V` instead of `v`.

**Comment by Slamy** [comment] 2017-05-30 20:25
There you go.
I tried to reduce what I currently have to something that crashes with -o1.
It's very sensitive on that. Adding a single print "heals" the program.

m68k-amigaos-gcc -v
   gcc-Version 6.3.1b 20170529-215512 (GCC) 

Use the following commands to build it. I've added a define that includes an additional print which heals the software:

m68k-amigaos-gcc -mcrt=nix13 -mcpu=68000 -Wall -O1 -fbbb=+V -DEXTRAPRINT -o working notWorking.c 
m68k-amigaos-gcc -mcrt=nix13 -mcpu=68000 -Wall -O1 -fbbb=+V -o notWorking notWorking.c

I tried to get into the assembly code generated by both. But there are very different.
I even have attached the binaries to be sure.

[o1NotWorking.zip](https://github.com/bebbo/amigaos-cross-toolchain/files/1039590/o1NotWorking.zip)

**Comment by bebbo** [comment] 2017-05-30 20:40
Thanks - there is a bug in dropping the stack frame. Workaround until it's fixed: -fomit-frame-pointer.

**Comment by Slamy** [comment] 2017-05-30 21:06
Whoah, you really are experienced with this stuff. I wish I could have the knowledge to be a better help with these compiler issues.

I can confirm that using this workaround allows -O1 and -O2 on the attached example.
Sadly my whole project seems to crash with -O2. I will investigate tomorrow.

**Comment by bebbo** [comment] 2017-05-30 21:22
pushed a fix.

**Comment by bebbo** [comment] 2017-05-31 15:20
my fault - forgot to push the submodule's gcc-6-branch

**Comment by bebbo** [comment] 2017-06-05 09:43
please test with current release

**Comment by Slamy** [comment] 2017-06-06 18:16
I can confirm that my project runs with "-O1 -fno-exceptions". As I don't use exceptions I decided to turn them off. So I'm happy with that.
But it seems by using only -O1 the program crashes. I'm not concered but maybe you are.
So I've made a small program which allows reproduction.
Kinda scary is that with just -O2 it works.

This one crashes:
m68k-amigaos-g++ -mcrt=nix13 -mcpu=68000 -Wall -O1 -fbbb=+V -o notWorking game.cpp Unit.cpp

These are stable:
m68k-amigaos-g++ -mcrt=nix13 -mcpu=68000 -Wall -O2 -fbbb=+V -o working game.cpp Unit.cpp
m68k-amigaos-g++ -mcrt=nix13 -mcpu=68000 -Wall -O2 -fno-exceptions -fbbb=+V -o working2 game.cpp Unit.cpp
m68k-amigaos-g++ -mcrt=nix13 -mcpu=68000 -Wall -O1 -fno-exceptions -fbbb=+V -o working3 game.cpp Unit.cpp

[o1NotWorkingExceptions.zip](https://github.com/bebbo/amigaos-cross-toolchain/files/1056010/o1NotWorkingExceptions.zip)

**Comment by bebbo** [comment] 2017-06-06 18:43
You found another bug in shrinking the stack frame. The verbose output differs, and with -O1 there is also

> :bbb: (f) dropping unused frame pointer
> :bbb: (f) adjusting exit sp

I'll look into it soon

**Comment by bebbo** [comment] 2017-06-07 11:09
I'm not 100% sure that my guesses are correct, but it's related to exception handlers code and the structures referring to these. For now stack frame removal of even unused frames is disabled in functions with exception handlers.

**Comment by bebbo** [comment] 2017-06-11 11:25
please test again

**Comment by alexalkis** [comment] 2017-06-11 14:27
hello-ks13 prints hello and gives software failure for me too.
On a A500 config (+8mb fast ram, tried with nofastmem also though) the command I've used was
`m68k-amigaos-gcc -O3 -s -mcrt=nix13 -fbaserel -m68000 -msmall-code -Wall -fomit-frame-pointer -o hello-ks13 hello-ks13.c`

**Comment by bebbo** [comment] 2017-06-11 15:07
Could you please upload your binary hello-ks13?

**Comment by alexalkis** [comment] 2017-06-11 15:35
Sure, here.
[hello-ks13.zip](https://github.com/bebbo/amigaos-cross-toolchain/files/1066555/hello-ks13.zip)

**Comment by Slamy** [comment] 2017-06-11 19:48
I've tested it again. Only having "-O1" seems to be stable now.
I can also confirm that hello-ks13 does crash in the end while my c++ project and hello-stdio.nix13 exit just fine.
@alexalkis Maybe you should go for that one to start if you need the stdio lib. I for myself am just too much in love with printf for debugging :-)

**Comment by bebbo** [comment] 2017-06-11 20:08
my apologies - I forgot to lock the a4 register. So all baserel stuff is broken atm

**Comment by bebbo** [comment] 2017-06-12 13:00
okies - examples are working again.

**Comment by alexalkis** [comment] 2017-06-12 15:26
-fbaserel still hangs the execution, right after printing "Hello world".
Without -fbaserel everything works as expected.

**Comment by alexalkis** [comment] 2017-06-12 15:45
Also, the following source
```
#include <stdio.h>

int main(int argc, char *argv[])
{
  printf("Hello world\n");
  return 0;
}

```
Compiles fine with
`m68k-amigaos-gcc -O3 -s -mcrt=nix13 -Wall -msmall-code -fomit-frame-pointer -o hello-ks13 hello.c`

but when run (in A500 config), it popups a requester saying it needs version 37 of dos.library. (Btw, exactly the same behavior I get from gcc-3.4.0)

Is that fixable? Shouldn't using crt for 1.3 make executables eligible for 1.3?

**Comment by bebbo** [comment] 2017-06-12 16:28
It's fixable. Right now the version is in libstubs and defaults to 37...

moving the corresponding file to libnix20 / libnix13 and setting it to 34 in libnix13.a should help.

**Comment by bebbo** [comment] 2017-06-13 15:07
Here we go: the remaining problem with the examples was a bogus link order... And libnix13 is now using version 34 on opening libraries.

Please test

**Comment by alexalkis** [comment] 2017-06-13 16:36
hello-ks13.c still needs to remove -fbaserel or it hangs.

hello.c (simple stdio for ks13) doesn't pop-up the "need 37 version of dos" requester but hangs.

**Comment by bebbo** [comment] 2017-06-13 17:02
[examples.zip](https://github.com/bebbo/amigaos-cross-toolchain/files/1072219/examples.zip)

all are running here /shrug
also the data/bss variables are looking in my debugger

**Comment by alexalkis** [comment] 2017-06-13 17:54
Are you using the default makefile?
try the default makefile and 'make hello-ks13'
(your exe size in zip is 556 bytes, the exe from the makefile comes out at 20684 bytes)

**Comment by bebbo** [comment] 2017-06-13 19:28
the default makefile includes debug information -> the files are not compareable since e.g. your path is in the file which differs from mine (20660 bytes).

Are you using a real A500?

If using *UAE ensure that cycle exact 1x cpu speed is selected

**Comment by alexalkis** [comment] 2017-06-13 20:20
This is so weird.  I am using fs-uae on a linux vm.
Here my A500 config
[```
config]
joystick_port_1 = nothing
amiga_model = A500
writable_floppy_images=1
floppy_drive_0_sounds = off
floppy_drive_1_sounds = off
fast_memory = 8192
video_sync_method =swap-fence
console_debugger = 1
hard_drive_0 = /home/alex/Documents/FS-UAE/Hard Drives/Amiga13
hard_drive_0_label = Work
```
I fired up my a1200 emulation and tried the ks13 executables and they run without problems!!!

Something must be up with my A500 emulation setup?  Will try to investigate....

**Comment by alexalkis** [comment] 2017-06-13 22:01
Works with another a500 (new hardfile, copied from another pc).  Messed up workbench or something?

Bottom line, I think we are good! :)

**Closed** 2017-06-14 08:03 UTC
